/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AuthLayoutSignInRouteImport } from './routes/auth/_layout/sign-in'
import { Route as AuthLayoutCreateAccountRouteImport } from './routes/auth/_layout/create-account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutUsersIndexRouteImport } from './routes/admin/_layout/users/index'
import { Route as AuthLayoutAdminSignInRouteImport } from './routes/auth/_layout/admin/sign-in'
import { Route as AuthLayoutAdminResetPasswordRouteImport } from './routes/auth/_layout/admin/reset-password'
import { Route as AdminLayoutUsersUserIdRouteImport } from './routes/admin/_layout/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AuthLayoutSignInRoute = AuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutCreateAccountRoute = AuthLayoutCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersIndexRoute = AdminLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AuthLayoutAdminSignInRoute = AuthLayoutAdminSignInRouteImport.update({
  id: '/admin/sign-in',
  path: '/admin/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminResetPasswordRoute =
  AuthLayoutAdminResetPasswordRouteImport.update({
    id: '/admin/reset-password',
    path: '/admin/reset-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AdminLayoutUsersUserIdRoute = AdminLayoutUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/create-account': typeof AuthLayoutCreateAccountRoute
  '/auth/sign-in': typeof AuthLayoutSignInRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/auth/admin/reset-password': typeof AuthLayoutAdminResetPasswordRoute
  '/auth/admin/sign-in': typeof AuthLayoutAdminSignInRoute
  '/admin/users/': typeof AdminLayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/create-account': typeof AuthLayoutCreateAccountRoute
  '/auth/sign-in': typeof AuthLayoutSignInRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/auth/admin/reset-password': typeof AuthLayoutAdminResetPasswordRoute
  '/auth/admin/sign-in': typeof AuthLayoutAdminSignInRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/_layout/create-account': typeof AuthLayoutCreateAccountRoute
  '/auth/_layout/sign-in': typeof AuthLayoutSignInRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/auth/_layout/admin/reset-password': typeof AuthLayoutAdminResetPasswordRoute
  '/auth/_layout/admin/sign-in': typeof AuthLayoutAdminSignInRoute
  '/admin/_layout/users/': typeof AdminLayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/auth/$'
    | '/auth/create-account'
    | '/auth/sign-in'
    | '/admin/'
    | '/admin/users/$userId'
    | '/auth/admin/reset-password'
    | '/auth/admin/sign-in'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/auth/create-account'
    | '/auth/sign-in'
    | '/admin'
    | '/admin/users/$userId'
    | '/auth/admin/reset-password'
    | '/auth/admin/sign-in'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/auth/_layout'
    | '/api/auth/$'
    | '/auth/_layout/create-account'
    | '/auth/_layout/sign-in'
    | '/admin/_layout/'
    | '/admin/_layout/users/$userId'
    | '/auth/_layout/admin/reset-password'
    | '/auth/_layout/admin/sign-in'
    | '/admin/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/auth/_layout/sign-in': {
      id: '/auth/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/create-account': {
      id: '/auth/_layout/create-account'
      path: '/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthLayoutCreateAccountRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users/': {
      id: '/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminLayoutUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/auth/_layout/admin/sign-in': {
      id: '/auth/_layout/admin/sign-in'
      path: '/admin/sign-in'
      fullPath: '/auth/admin/sign-in'
      preLoaderRoute: typeof AuthLayoutAdminSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/admin/reset-password': {
      id: '/auth/_layout/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/auth/admin/reset-password'
      preLoaderRoute: typeof AuthLayoutAdminResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/admin/_layout/users/$userId': {
      id: '/admin/_layout/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminLayoutUsersUserIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutUsersUserIdRoute: typeof AdminLayoutUsersUserIdRoute
  AdminLayoutUsersIndexRoute: typeof AdminLayoutUsersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutUsersUserIdRoute: AdminLayoutUsersUserIdRoute,
  AdminLayoutUsersIndexRoute: AdminLayoutUsersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutCreateAccountRoute: typeof AuthLayoutCreateAccountRoute
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
  AuthLayoutAdminResetPasswordRoute: typeof AuthLayoutAdminResetPasswordRoute
  AuthLayoutAdminSignInRoute: typeof AuthLayoutAdminSignInRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutCreateAccountRoute: AuthLayoutCreateAccountRoute,
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
  AuthLayoutAdminResetPasswordRoute: AuthLayoutAdminResetPasswordRoute,
  AuthLayoutAdminSignInRoute: AuthLayoutAdminSignInRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
