/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as AuthLayoutIndexRouteImport } from './routes/auth/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as DashboardOrganizationsNewRouteImport } from './routes/dashboard/organizations/new'
import { Route as AuthLayoutSignInRouteImport } from './routes/auth/_layout/sign-in'
import { Route as AuthLayoutResetPasswordRouteImport } from './routes/auth/_layout/reset-password'
import { Route as AuthLayoutCreateAccountRouteImport } from './routes/auth/_layout/create-account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminPermissionAuditRouteImport } from './routes/api/admin/permission-audit'
import { Route as AdminLayoutUsersIndexRouteImport } from './routes/admin/_layout/users/index'
import { Route as AdminLayoutReportsIndexRouteImport } from './routes/admin/_layout/reports/index'
import { Route as DashboardOrganizationsOrgIdTeamsRouteImport } from './routes/dashboard/organizations/$orgId/teams'
import { Route as DashboardOrganizationsOrgIdMembersRouteImport } from './routes/dashboard/organizations/$orgId/members'
import { Route as AdminLayoutUsersUserIdRouteImport } from './routes/admin/_layout/users/$userId'
import { Route as AdminLayoutReportsReportIdRouteImport } from './routes/admin/_layout/reports/$reportId'
import { Route as AdminLayoutInvestorsVerificationRouteImport } from './routes/admin/_layout/investors/verification'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLayoutIndexRoute = AuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const DashboardOrganizationsNewRoute =
  DashboardOrganizationsNewRouteImport.update({
    id: '/dashboard/organizations/new',
    path: '/dashboard/organizations/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLayoutSignInRoute = AuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutResetPasswordRoute = AuthLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutCreateAccountRoute = AuthLayoutCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPermissionAuditRoute = ApiAdminPermissionAuditRouteImport.update({
  id: '/api/admin/permission-audit',
  path: '/api/admin/permission-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersIndexRoute = AdminLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReportsIndexRoute = AdminLayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const DashboardOrganizationsOrgIdTeamsRoute =
  DashboardOrganizationsOrgIdTeamsRouteImport.update({
    id: '/dashboard/organizations/$orgId/teams',
    path: '/dashboard/organizations/$orgId/teams',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardOrganizationsOrgIdMembersRoute =
  DashboardOrganizationsOrgIdMembersRouteImport.update({
    id: '/dashboard/organizations/$orgId/members',
    path: '/dashboard/organizations/$orgId/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLayoutUsersUserIdRoute = AdminLayoutUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReportsReportIdRoute =
  AdminLayoutReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutInvestorsVerificationRoute =
  AdminLayoutInvestorsVerificationRouteImport.update({
    id: '/investors/verification',
    path: '/investors/verification',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/api/admin/permission-audit': typeof ApiAdminPermissionAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/create-account': typeof AuthLayoutCreateAccountRoute
  '/auth/reset-password': typeof AuthLayoutResetPasswordRoute
  '/auth/sign-in': typeof AuthLayoutSignInRoute
  '/dashboard/organizations/new': typeof DashboardOrganizationsNewRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/auth/': typeof AuthLayoutIndexRoute
  '/admin/investors/verification': typeof AdminLayoutInvestorsVerificationRoute
  '/admin/reports/$reportId': typeof AdminLayoutReportsReportIdRoute
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/organizations/$orgId/teams': typeof DashboardOrganizationsOrgIdTeamsRoute
  '/admin/reports/': typeof AdminLayoutReportsIndexRoute
  '/admin/users/': typeof AdminLayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/admin/permission-audit': typeof ApiAdminPermissionAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/create-account': typeof AuthLayoutCreateAccountRoute
  '/auth/reset-password': typeof AuthLayoutResetPasswordRoute
  '/auth/sign-in': typeof AuthLayoutSignInRoute
  '/dashboard/organizations/new': typeof DashboardOrganizationsNewRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/auth': typeof AuthLayoutIndexRoute
  '/admin/investors/verification': typeof AdminLayoutInvestorsVerificationRoute
  '/admin/reports/$reportId': typeof AdminLayoutReportsReportIdRoute
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/organizations/$orgId/teams': typeof DashboardOrganizationsOrgIdTeamsRoute
  '/admin/reports': typeof AdminLayoutReportsIndexRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/api/admin/permission-audit': typeof ApiAdminPermissionAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/_layout/create-account': typeof AuthLayoutCreateAccountRoute
  '/auth/_layout/reset-password': typeof AuthLayoutResetPasswordRoute
  '/auth/_layout/sign-in': typeof AuthLayoutSignInRoute
  '/dashboard/organizations/new': typeof DashboardOrganizationsNewRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/auth/_layout/': typeof AuthLayoutIndexRoute
  '/admin/_layout/investors/verification': typeof AdminLayoutInvestorsVerificationRoute
  '/admin/_layout/reports/$reportId': typeof AdminLayoutReportsReportIdRoute
  '/admin/_layout/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/organizations/$orgId/teams': typeof DashboardOrganizationsOrgIdTeamsRoute
  '/admin/_layout/reports/': typeof AdminLayoutReportsIndexRoute
  '/admin/_layout/users/': typeof AdminLayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v2'
    | '/accept-invitation/$invitationId'
    | '/admin'
    | '/auth'
    | '/api/admin/permission-audit'
    | '/api/auth/$'
    | '/auth/create-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/organizations/new'
    | '/admin/'
    | '/auth/'
    | '/admin/investors/verification'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/organizations/$orgId/teams'
    | '/admin/reports/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/v2'
    | '/accept-invitation/$invitationId'
    | '/api/admin/permission-audit'
    | '/api/auth/$'
    | '/auth/create-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/organizations/new'
    | '/admin'
    | '/auth'
    | '/admin/investors/verification'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/organizations/$orgId/teams'
    | '/admin/reports'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/v2'
    | '/accept-invitation/$invitationId'
    | '/admin/_layout'
    | '/auth/_layout'
    | '/api/admin/permission-audit'
    | '/api/auth/$'
    | '/auth/_layout/create-account'
    | '/auth/_layout/reset-password'
    | '/auth/_layout/sign-in'
    | '/dashboard/organizations/new'
    | '/admin/_layout/'
    | '/auth/_layout/'
    | '/admin/_layout/investors/verification'
    | '/admin/_layout/reports/$reportId'
    | '/admin/_layout/users/$userId'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/organizations/$orgId/teams'
    | '/admin/_layout/reports/'
    | '/admin/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V2Route: typeof V2Route
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ApiAdminPermissionAuditRoute: typeof ApiAdminPermissionAuditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardOrganizationsNewRoute: typeof DashboardOrganizationsNewRoute
  DashboardOrganizationsOrgIdMembersRoute: typeof DashboardOrganizationsOrgIdMembersRoute
  DashboardOrganizationsOrgIdTeamsRoute: typeof DashboardOrganizationsOrgIdTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout/': {
      id: '/auth/_layout/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/dashboard/organizations/new': {
      id: '/dashboard/organizations/new'
      path: '/dashboard/organizations/new'
      fullPath: '/dashboard/organizations/new'
      preLoaderRoute: typeof DashboardOrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout/sign-in': {
      id: '/auth/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/reset-password': {
      id: '/auth/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthLayoutResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/create-account': {
      id: '/auth/_layout/create-account'
      path: '/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthLayoutCreateAccountRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/permission-audit': {
      id: '/api/admin/permission-audit'
      path: '/api/admin/permission-audit'
      fullPath: '/api/admin/permission-audit'
      preLoaderRoute: typeof ApiAdminPermissionAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users/': {
      id: '/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminLayoutUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/': {
      id: '/admin/_layout/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminLayoutReportsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/dashboard/organizations/$orgId/teams': {
      id: '/dashboard/organizations/$orgId/teams'
      path: '/dashboard/organizations/$orgId/teams'
      fullPath: '/dashboard/organizations/$orgId/teams'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organizations/$orgId/members': {
      id: '/dashboard/organizations/$orgId/members'
      path: '/dashboard/organizations/$orgId/members'
      fullPath: '/dashboard/organizations/$orgId/members'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users/$userId': {
      id: '/admin/_layout/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminLayoutUsersUserIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/$reportId': {
      id: '/admin/_layout/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminLayoutReportsReportIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/investors/verification': {
      id: '/admin/_layout/investors/verification'
      path: '/investors/verification'
      fullPath: '/admin/investors/verification'
      preLoaderRoute: typeof AdminLayoutInvestorsVerificationRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutInvestorsVerificationRoute: typeof AdminLayoutInvestorsVerificationRoute
  AdminLayoutReportsReportIdRoute: typeof AdminLayoutReportsReportIdRoute
  AdminLayoutUsersUserIdRoute: typeof AdminLayoutUsersUserIdRoute
  AdminLayoutReportsIndexRoute: typeof AdminLayoutReportsIndexRoute
  AdminLayoutUsersIndexRoute: typeof AdminLayoutUsersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutInvestorsVerificationRoute: AdminLayoutInvestorsVerificationRoute,
  AdminLayoutReportsReportIdRoute: AdminLayoutReportsReportIdRoute,
  AdminLayoutUsersUserIdRoute: AdminLayoutUsersUserIdRoute,
  AdminLayoutReportsIndexRoute: AdminLayoutReportsIndexRoute,
  AdminLayoutUsersIndexRoute: AdminLayoutUsersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutCreateAccountRoute: typeof AuthLayoutCreateAccountRoute
  AuthLayoutResetPasswordRoute: typeof AuthLayoutResetPasswordRoute
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutCreateAccountRoute: AuthLayoutCreateAccountRoute,
  AuthLayoutResetPasswordRoute: AuthLayoutResetPasswordRoute,
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V2Route: V2Route,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ApiAdminPermissionAuditRoute: ApiAdminPermissionAuditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardOrganizationsNewRoute: DashboardOrganizationsNewRoute,
  DashboardOrganizationsOrgIdMembersRoute:
    DashboardOrganizationsOrgIdMembersRoute,
  DashboardOrganizationsOrgIdTeamsRoute: DashboardOrganizationsOrgIdTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
